import { motion } from 'framer-motion'
import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import PageHero from '../components/PageHero'
import SEO from '../components/SEO'
import Reveal from '../components/Reveal'
import SectionHeading from '../components/SectionHeading'
import StatCounter from '../components/StatCounter'
import { stats, values } from '../data/siteData'

export default function About() {
  return <motion.main id="main-content" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
    <SEO title="About Us" description="Meet Krishna Madhav Agency, a textile commission agent with offices in Surat, Delhi and Jaipur." />
    <PageHero eyebrow="About us" title="One textile agency. Three important markets." text="Krishna Madhav Agency represents textile trade across Surat, Delhi and Jaipur, dealing in sarees, lehengas, suits and garments." image="https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1800&q=85" />
    <section className="section-space"><div className="container-site grid items-center gap-14 lg:grid-cols-2 lg:gap-20"><Reveal><div className="relative"><img src="https://images.unsplash.com/photo-1583845112203-29329902332e?auto=format&fit=crop&w=1100&q=85" alt="Premium textile detail" className="h-[460px] w-full rounded-[2rem] object-cover shadow-soft sm:h-[580px]" /><div className="absolute -bottom-7 -right-3 max-w-[220px] rounded-3xl bg-gold p-6 text-ink shadow-xl sm:-right-7"><p className="font-display text-3xl font-extrabold">3 Offices</p><p className="mt-2 text-xs font-bold leading-5">Surat • Delhi • Jaipur</p></div></div></Reveal><Reveal delay={.1}><SectionHeading eyebrow="Our identity" title="Professional textile commission representation across markets." text="Krishna Madhav Agency is a textile commission agent led by Mahendra Bhai and Ramavtar Sharma. The agency maintains offices in Surat, Delhi and Jaipur and deals in sarees, lehengas, suits, readymade garments and garments." /><p className="mt-5 leading-7 text-slate-600">Our role is to keep textile trade conversations direct and coordinated—from understanding the requirement and making the right connection through commercial discussion and order follow-up.</p><ul className="mt-7 grid gap-3 sm:grid-cols-2">{['Surat office', 'Delhi office', 'Jaipur office', 'Direct principal contacts'].map(x => <li key={x} className="flex items-center gap-2 text-sm font-semibold text-ink"><CheckCircle2 size={18} className="text-gold" />{x}</li>)}</ul></Reveal></div></section>
    <section className="bg-ink py-14"><div className="container-site grid grid-cols-2 gap-8 md:grid-cols-4">{stats.map(x => <StatCounter key={x.label} {...x} dark />)}</div></section>
    <section className="section-space bg-mist"><div className="container-site"><Reveal><SectionHeading eyebrow="What guides us" title="Good business, woven from good principles." align="center" /></Reveal><div className="mt-12 grid gap-5 md:grid-cols-2">{values.map(({ icon: Icon, title, text }, i) => <Reveal key={title} delay={(i % 2) * .07}><div className="card flex h-full gap-5 p-7"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-gold-light/20 text-gold-dark"><Icon size={22} /></span><div><h3 className="font-display text-lg font-bold text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></div></div></Reveal>)}</div></div></section>
    {/* TODO: Confirm the formal mission and vision statements with the company. */}
    <section className="section-space"><div className="container-site grid gap-8 lg:grid-cols-2"><Reveal><div className="h-full rounded-[2rem] bg-cream p-8 sm:p-10"><span className="eyebrow">Our purpose</span><h2 className="mt-5 font-display text-3xl font-bold tracking-tight text-ink">Make textile trade clearer and easier to coordinate.</h2><p className="mt-5 leading-7 text-slate-600">We add value by connecting relevant trade partners, aligning commercial conversations and staying responsive through the process.</p></div></Reveal><Reveal delay={.1}><div className="h-full rounded-[2rem] bg-ink p-8 text-white sm:p-10"><span className="eyebrow">Our direction</span><h2 className="mt-5 font-display text-3xl font-bold tracking-tight">Think beyond a single market.</h2><p className="mt-5 leading-7 text-slate-400">With a presence across Surat, Delhi and Jaipur, we help textile requirements move through a broader and more connected trade network.</p></div></Reveal></div></section>
    <section className="pb-20 sm:pb-28"><div className="container-site"><Reveal><div className="flex flex-col items-center justify-between gap-6 rounded-[2rem] bg-gold p-8 text-center sm:p-12 lg:flex-row lg:text-left"><div><h2 className="font-display text-3xl font-bold tracking-tight text-ink">Let’s build a dependable supply relationship.</h2><p className="mt-2 text-sm text-slate-700">Tell us what you are looking for. We will take it from there.</p></div><Link to="/contact" className="btn-secondary shrink-0 !border-transparent">Talk to our team <ArrowRight size={17} /></Link></div></Reveal></div></section>
  </motion.main>
}
