import { motion } from 'framer-motion'
import { ArrowRight, Check } from 'lucide-react'
import { Link } from 'react-router-dom'
import PageHero from '../components/PageHero'
import SEO from '../components/SEO'
import Reveal from '../components/Reveal'
import SectionHeading from '../components/SectionHeading'
import { process, services } from '../data/siteData'

// TODO: Confirm these service sub-points against the company's exact operating process.
const inclusions = ['Requirement discussion', 'Relevant trade connection', 'Commercial negotiation', 'Product coordination', 'Order follow-up', 'Multi-city communication']

export default function Services() {
  return <motion.main id="main-content" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
    <SEO title="Services" description="Textile commission agency, product sourcing and trade coordination across Surat, Delhi and Jaipur." />
    <PageHero eyebrow="Services" title="Textile commission agency support across three markets." text="Direct representation and coordination for sarees, lehengas, suits, readymade garments and garments." image="https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=1800&q=85" />
    <section className="section-space"><div className="container-site"><Reveal><SectionHeading eyebrow="Our expertise" title="Practical textile trade support." text="Krishna Madhav Agency connects requirements, commercial conversations and market coordination through its Surat, Delhi and Jaipur presence." align="center" /></Reveal><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{services.map(({ icon: Icon, title, text }, i) => <Reveal key={title} delay={(i % 3) * .07}><article className="group h-full rounded-3xl border border-slate-200 bg-white p-7 shadow-card transition hover:-translate-y-2 hover:border-gold-light"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-ink text-gold"><Icon size={24} /></span><span className="font-display text-xs font-bold text-slate-300">0{i + 1}</span></div><h2 className="mt-7 font-display text-xl font-bold text-ink">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p><ul className="mt-6 space-y-2 border-t border-slate-100 pt-5">{inclusions.slice(i % 3, i % 3 + 3).map(x => <li key={x} className="flex items-center gap-2 text-xs font-semibold text-slate-500"><Check size={14} className="text-gold" /> {x}</li>)}</ul></article></Reveal>)}</div></div></section>
    <section className="section-space bg-mist"><div className="container-site grid items-center gap-14 lg:grid-cols-[.85fr_1.15fr]"><Reveal><SectionHeading eyebrow="Built for momentum" title="We manage the gaps where textile orders usually slow down." text="A successful order is not just a match between buyer and seller. It is dozens of details staying aligned across commercial, technical and production conversations." /><p className="mt-5 text-sm leading-7 text-slate-600">Our role is to protect that alignment. We anticipate questions, surface changes early, and help both sides reach practical solutions without unnecessary escalation.</p><Link to="/contact" className="btn-primary mt-8">Discuss your requirement <ArrowRight size={17} /></Link></Reveal><Reveal delay={.1}><div className="relative overflow-hidden rounded-[2rem]"><img src="https://images.unsplash.com/photo-1598554747436-c9293d6a588f?auto=format&fit=crop&w=1200&q=85" alt="Garment manufacturing team" className="h-[480px] w-full object-cover" /><div className="absolute inset-x-5 bottom-5 rounded-2xl border border-white/20 bg-ink/85 p-5 text-white backdrop-blur-lg"><p className="font-display text-lg font-bold">One point of coordination</p><p className="mt-1 text-sm text-slate-300">Less fragmented communication. More confident decisions.</p></div></div></Reveal></div></section>
    <section className="section-space bg-ink text-white"><div className="container-site"><Reveal><SectionHeading eyebrow="Our workflow" title="Designed for clarity, from first call to trade completion." light align="center" /></Reveal><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{process.map((item, i) => <Reveal key={item.step} delay={(i % 3) * .06}><div className="h-full rounded-2xl border border-white/10 bg-white/[.04] p-6"><span className="text-xs font-bold text-gold">STEP {item.step}</span><h3 className="mt-4 font-display text-lg font-bold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{item.text}</p></div></Reveal>)}</div></div></section>
  </motion.main>
}
